modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nmc"
version = "${version}"
displayName = "No Man Craft"
authors = "TATHAN"
description = '''
Explore an infinity of Planets !
'''
logoFile = "nmc.png"

[[dependencies.nmc]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nmc]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nmc]]
modId = "stellaris"
type = "required"
versionRange = "[1.3.5,)"
ordering = "BEFORE"
side = "BOTH"



[[mixins]]
config = "nmc.mixins.json"
